prepare:
    path: /p/{accessCode}
    controller: App\Controller\SecretSantaController::prepareSubmission

submit:
    path: /submit
    controller: App\Controller\SecretSantaController::storeSubmission


index:
    path: /
    controller: App\Controller\SecretSantaController::index
